### ISSUE TITLE
how do you ignore typekit fonts? it uses 'script' instead of 'link' like google fonts

### ISSUE THREAD

**Issue by kn00tcn** [chuckcarpenter/REM-unit-polyfill#61]
maybe a nice feature would be a whitelist of what the polyfill should scan

EDIT: well i manually altered it

line 17 from `styles[i].getAttribute('data-norem') === null` to `styles[i].getAttribute('href').search('YOURFILENAME') > 0`

doesnt have to be the exact filename, you could simply have a prefix or suffix string

[indexOf might also work](https://stackoverflow.com/questions/1789945/how-can-i-check-if-one-string-contains-another-substring)

**Comment by chuckcarpenter** [comment]
@kn00tcn I see where that works for your use case. Perhaps either having it ignore any element with `data-norem` or an API on setup to ignore files? Either way, we'd welcome a pull request if you sort through an abstract way to deal with that issue.
