### ISSUE TITLE
"Access is denied" javascript error

### ISSUE THREAD

**Issue by cbracco** [chuckcarpenter/REM-unit-polyfill#7]
Hello again :)

I'm here to bother you folks one more time. When debugging [my personal site](http://cbracco.me) in IE8 with your polyfill included before the body tag (in plugins.js), I am getting a console error which is pictured in the screenshot below.

![Screen Shot 2013-02-12 at 1 00 22 PM](https://f.cloud.github.com/assets/1480677/149940/a7b70e00-753e-11e2-8c20-ede20976a4ad.png)

I feel like I've run across this issue before (something to do with cross domain policies, perhaps?) but I can't seem to find a remedy. Any help is greatly appreciated!

Thanks,
Chris

**Comment by rickcurran** [comment]
Hi, sorry for posting on an old closed issue, but I am seeing this error in IE8 but I am not accessing any files on different domains or subdomains. I'd previously used the polyfill on another site and it worked at the time I launched it, but checking this just now I'm seeing the 'access denied' error message on that site although it previously had been working. I have tried adding "Access-Control-Allow-Origin: *" header to the site but this didn't fix the problem. Any suggestions?
